# Generated by Django 4.0.8 on 2022-11-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
