# Generated by Django 4.0.8 on 2022-12-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_importer_historicalevent_importer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='importer',
            new_name='importer_user',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='importer',
            new_name='importer_user',
        ),
    ]
