# Generated by Django 4.0.8 on 2023-01-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_importer_event_importer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='event',
            name='clong',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='clat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='clong',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
