# Generated by Django 4.1.7 on 2023-03-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_logrecord_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='is_admin_only',
            field=models.BooleanField(default=False),
        ),
    ]
