# Generated by Django 4.0.8 on 2022-11-15 16:22

from django.db import migrations, models
import main.validators
import utils.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_storage.avatar_property_avatar_path, validators=[main.validators.validate_avatar_max_size], verbose_name='Avatar image'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Client'), (1, 'Publisher'), (2, 'Staff')], default=0, verbose_name='User type'),
        ),
    ]
