# Generated by Django 4.1.2 on 2022-10-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='document_scan',
        ),
    ]
