# Generated by Django 4.1.2 on 2022-10-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='gt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='prid',
            field=models.IntegerField(),
        ),
    ]
