# Generated by Django 4.1.2 on 2022-10-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_chzrecord_gt_alter_chzrecord_prid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='prid',
            field=models.CharField(max_length=255),
        ),
    ]
