# Generated by Django 4.1.2 on 2022-10-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_dgisrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dgisrecord',
            old_name='project',
            new_name='project_publications',
        ),
        migrations.RemoveField(
            model_name='dgisrecord',
            name='publications',
        ),
    ]
