# Generated by Django 4.1.2 on 2022-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_project_dgisrecord_project_publications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='phone_area_code',
            field=models.CharField(max_length=1024, verbose_name='Код телефонной зоны'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='phones',
            field=models.CharField(max_length=1024, verbose_name='Телефоны'),
        ),
    ]
