# Generated by Django 4.1.2 on 2022-10-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_dgisrecord_categories_alter_dgisrecord_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='address',
            field=models.CharField(max_length=1024, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='branch_legal_name',
            field=models.CharField(max_length=1024, verbose_name='Юридическое название филиала'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='branch_org_name',
            field=models.CharField(max_length=1024, verbose_name='Организационно-правовая форма филиала'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='brand',
            field=models.CharField(max_length=1024, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='building_purpose',
            field=models.CharField(max_length=1024, verbose_name='Назначение здания'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='division',
            field=models.CharField(max_length=1024, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='division_extension',
            field=models.CharField(max_length=1024, verbose_name='Расширение подразделения'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='extension',
            field=models.CharField(max_length=1024, verbose_name='Расширение'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='extension_addition',
            field=models.CharField(max_length=1024, verbose_name='Дополнение к расширению'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='legal_name',
            field=models.CharField(max_length=1024, verbose_name='Юридическое название'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='number_of_floors',
            field=models.CharField(max_length=1024, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='org_form',
            field=models.CharField(max_length=1024, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='project_publications',
            field=models.CharField(max_length=1024, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='street',
            field=models.CharField(max_length=1024, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='unit',
            field=models.CharField(max_length=1024, verbose_name='Единица территориального деления'),
        ),
    ]
