# Generated by Django 4.1.2 on 2022-10-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_dgisrecord_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='address',
            field=models.CharField(max_length=2048, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='branch_legal_name',
            field=models.CharField(max_length=2048, verbose_name='Юридическое название филиала'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='branch_org_name',
            field=models.CharField(max_length=2048, verbose_name='Организационно-правовая форма филиала'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='brand',
            field=models.CharField(max_length=2048, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='building_purpose',
            field=models.CharField(max_length=2048, verbose_name='Назначение здания'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='categories',
            field=models.CharField(max_length=2048, verbose_name='Рубрики'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='division',
            field=models.CharField(max_length=2048, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='division_extension',
            field=models.CharField(max_length=2048, verbose_name='Расширение подразделения'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='emails',
            field=models.CharField(max_length=2048, verbose_name='Адреса электронной почты'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='extension',
            field=models.CharField(max_length=2048, verbose_name='Расширение'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='extension_addition',
            field=models.CharField(max_length=2048, verbose_name='Дополнение к расширению'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='inn_ogrn',
            field=models.CharField(max_length=2048, verbose_name='ИНН/ОГРН'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='legal_name',
            field=models.CharField(max_length=2048, verbose_name='Юридическое название'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='number_of_floors',
            field=models.CharField(max_length=2048, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='org_form',
            field=models.CharField(max_length=2048, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='phone_area_code',
            field=models.CharField(max_length=2048, verbose_name='Код телефонной зоны'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='phones',
            field=models.CharField(max_length=2048, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='project_publications',
            field=models.CharField(max_length=2048, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_facebook',
            field=models.CharField(max_length=2048, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_google_plus',
            field=models.CharField(max_length=2048, verbose_name='GooglePlus'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_icq',
            field=models.CharField(max_length=2048, verbose_name='Icq'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_instagram',
            field=models.CharField(max_length=2048, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_linkedin',
            field=models.CharField(max_length=2048, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_odnoklassniki',
            field=models.CharField(max_length=2048, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_pinterest',
            field=models.CharField(max_length=2048, verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_skype',
            field=models.CharField(max_length=2048, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_telegram',
            field=models.CharField(max_length=2048, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_twitter',
            field=models.CharField(max_length=2048, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_viber',
            field=models.CharField(max_length=2048, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_vk',
            field=models.CharField(max_length=2048, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_whatsapp',
            field=models.CharField(max_length=2048, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_work_time',
            field=models.CharField(max_length=2048, verbose_name='Графики работы'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_youtube',
            field=models.CharField(max_length=2048, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='street',
            field=models.CharField(max_length=2048, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='unit',
            field=models.CharField(max_length=2048, verbose_name='Единица территориального деления'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='web_alias',
            field=models.CharField(max_length=2048, verbose_name='Web-Алиас'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='web_sites',
            field=models.CharField(max_length=2048, verbose_name='Веб сайты'),
        ),
    ]
