# Generated by Django 4.1.2 on 2022-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_dgisrecord_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='phones',
            field=models.CharField(max_length=4096, verbose_name='Телефоны'),
        ),
    ]
