# Generated by Django 4.1.2 on 2022-10-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_dgisrecord_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='branch_org_name',
            field=models.CharField(max_length=2048, verbose_name='ОПФ филиала'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='org_form',
            field=models.CharField(max_length=2048, verbose_name='ОПФ'),
        ),
    ]
