# Generated by Django 4.1.2 on 2022-10-24 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_dgisrecord_branch_org_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgisrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dgisrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
