# Generated by Django 4.1.2 on 2022-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_dgisrecord_created_at_dgisrecord_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='phone_area_code',
            field=models.CharField(max_length=4096, verbose_name='Код телефонной зоны'),
        ),
    ]
