# Generated by Django 4.1.2 on 2022-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_dgisrecord_phone_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='phone_area_code',
            field=models.TextField(verbose_name='Код телефонной зоны'),
        ),
    ]
