# Generated by Django 4.1.2 on 2022-10-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_dgisrecord_phone_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='emails',
            field=models.TextField(max_length=2048, verbose_name='Адреса электронной почты'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='phones',
            field=models.TextField(max_length=4096, verbose_name='Телефоны'),
        ),
    ]
