# Generated by Django 4.1.2 on 2022-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_dgisrecord_emails_alter_dgisrecord_phones'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dgisrecord',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'legal_name', 'org_form', 'branch_legal_name', 'branch_org_name', 'extension', 'extension_addition', 'division', 'division_extension', 'project_publications', 'unit', 'street', 'address', 'number_of_floors', 'building_purpose', 'phone_area_code', 'phones', 'emails', 'web_alias', 'web_sites', 'soc_skype', 'soc_icq', 'soc_vk', 'soc_twitter', 'soc_facebook', 'soc_instagram', 'soc_linkedin', 'soc_pinterest', 'soc_youtube', 'soc_google_plus', 'soc_odnoklassniki', 'soc_whatsapp', 'soc_viber', 'soc_telegram', 'soc_work_time', 'categories', 'inn_ogrn'), name='unique_imported_fields'),
        ),
    ]
