# Generated by Django 4.1.2 on 2022-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_dgisrecord_emails_alter_dgisrecord_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='categories',
            field=models.TextField(verbose_name='Рубрики'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='emails',
            field=models.TextField(verbose_name='Адреса электронной почты'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='inn_ogrn',
            field=models.TextField(verbose_name='ИНН/ОГРН'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='phones',
            field=models.TextField(verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_facebook',
            field=models.TextField(verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_google_plus',
            field=models.TextField(verbose_name='GooglePlus'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_instagram',
            field=models.TextField(verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_linkedin',
            field=models.TextField(verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_odnoklassniki',
            field=models.TextField(verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_pinterest',
            field=models.TextField(verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_telegram',
            field=models.TextField(verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_twitter',
            field=models.TextField(verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_viber',
            field=models.TextField(verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_vk',
            field=models.TextField(verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_whatsapp',
            field=models.TextField(verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_work_time',
            field=models.TextField(verbose_name='Графики работы'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_youtube',
            field=models.TextField(verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='web_alias',
            field=models.TextField(verbose_name='Web-Алиас'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='web_sites',
            field=models.TextField(verbose_name='Веб сайты'),
        ),
    ]
