# Generated by Django 4.1.2 on 2022-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_dgisrecord_categories_alter_dgisrecord_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
