# Generated by Django 4.1.2 on 2022-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_dgisrecord_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='branch_legal_name',
            field=models.CharField(max_length=2048, verbose_name='Юр. название филиала'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='legal_name',
            field=models.CharField(max_length=2048, verbose_name='Юр. название'),
        ),
    ]
