# Generated by Django 4.1.2 on 2022-10-24 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_dgisrecord_branch_legal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='inn',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='ИНН'),
        ),
    ]
