# Generated by Django 4.1.2 on 2022-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_dgisrecord_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='name',
            field=models.TextField(verbose_name='Наименование организации'),
        ),
    ]
