# Generated by Django 4.1.2 on 2022-10-24 14:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0024_alter_dgisrecord_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDGisRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование организации')),
                ('brand', models.CharField(max_length=2048, verbose_name='Бренд')),
                ('inn', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, null=True, size=None, verbose_name='ИНН')),
                ('legal_name', models.CharField(max_length=2048, verbose_name='Юр. название')),
                ('org_form', models.CharField(max_length=2048, verbose_name='ОПФ')),
                ('branch_legal_name', models.CharField(max_length=2048, verbose_name='Юр. название филиала')),
                ('branch_org_name', models.CharField(max_length=2048, verbose_name='ОПФ филиала')),
                ('extension', models.CharField(max_length=2048, verbose_name='Расширение')),
                ('extension_addition', models.CharField(max_length=2048, verbose_name='Дополнение к расширению')),
                ('division', models.CharField(max_length=2048, verbose_name='Подразделение')),
                ('division_extension', models.CharField(max_length=2048, verbose_name='Расширение подразделения')),
                ('project_publications', models.CharField(max_length=2048, verbose_name='Проект')),
                ('unit', models.CharField(max_length=2048, verbose_name='Единица территориального деления')),
                ('street', models.CharField(max_length=2048, verbose_name='Улица')),
                ('address', models.CharField(max_length=2048, verbose_name='Адрес')),
                ('number_of_floors', models.CharField(max_length=2048, verbose_name='Этажность')),
                ('building_purpose', models.CharField(max_length=2048, verbose_name='Назначение здания')),
                ('phone_area_code', models.TextField(verbose_name='Код телефонной зоны')),
                ('phones', models.TextField(verbose_name='Телефоны')),
                ('emails', models.TextField(verbose_name='Адреса электронной почты')),
                ('web_alias', models.TextField(verbose_name='Web-Алиас')),
                ('web_sites', models.TextField(verbose_name='Веб сайты')),
                ('soc_skype', models.CharField(max_length=2048, verbose_name='Skype')),
                ('soc_icq', models.CharField(max_length=2048, verbose_name='Icq')),
                ('soc_vk', models.TextField(verbose_name='ВКонтакте')),
                ('soc_twitter', models.TextField(verbose_name='Twitter')),
                ('soc_facebook', models.TextField(verbose_name='Facebook')),
                ('soc_instagram', models.TextField(verbose_name='Instagram')),
                ('soc_linkedin', models.TextField(verbose_name='LinkedIn')),
                ('soc_pinterest', models.TextField(verbose_name='Pinterest')),
                ('soc_youtube', models.TextField(verbose_name='YouTube')),
                ('soc_google_plus', models.TextField(verbose_name='GooglePlus')),
                ('soc_odnoklassniki', models.TextField(verbose_name='Одноклассники')),
                ('soc_whatsapp', models.TextField(verbose_name='WhatsApp')),
                ('soc_viber', models.TextField(verbose_name='Viber')),
                ('soc_telegram', models.TextField(verbose_name='Telegram')),
                ('soc_work_time', models.TextField(verbose_name='Графики работы')),
                ('categories', models.TextField(verbose_name='Рубрики')),
                ('inn_ogrn', models.TextField(verbose_name='ИНН/ОГРН')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Запись 2Гис',
                'verbose_name_plural': 'historical Записи 2Гис',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCHZRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('owner_name', models.CharField(max_length=255)),
                ('prid', models.CharField(max_length=255)),
                ('gt', models.CharField(max_length=255)),
                ('pg_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('producer_name', models.CharField(max_length=255)),
                ('mrp', models.PositiveIntegerField()),
                ('in_russia', models.PositiveIntegerField()),
                ('out_total', models.PositiveIntegerField()),
                ('out_whosale', models.PositiveIntegerField()),
                ('out_retail', models.PositiveIntegerField()),
                ('out_recycle', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Запись ЧЗ',
                'verbose_name_plural': 'historical Записи ЧЗ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
