# Generated by Django 4.1.2 on 2022-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_chzrecord_is_edited_manually_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='is_edited_manually',
            field=models.BooleanField(default=False, verbose_name='Редактировано'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='is_edited_manually',
            field=models.BooleanField(default=False, verbose_name='Редактировано'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='is_edited_manually',
            field=models.BooleanField(default=False, verbose_name='Редактировано'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='is_edited_manually',
            field=models.BooleanField(default=False, verbose_name='Редактировано'),
        ),
    ]
