# Generated by Django 4.1.2 on 2022-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_chzrecord_created_at_chzrecord_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='branch_legal_name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Юр. название филиала'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='branch_org_name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='ОПФ филиала'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='categories',
            field=models.TextField(blank=True, null=True, verbose_name='Рубрики'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='division',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='division_extension',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Расширение подразделения'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='extension_addition',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Дополнение к расширению'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_facebook',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_google_plus',
            field=models.TextField(blank=True, null=True, verbose_name='GooglePlus'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_icq',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Icq'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_instagram',
            field=models.TextField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_linkedin',
            field=models.TextField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_odnoklassniki',
            field=models.TextField(blank=True, null=True, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_pinterest',
            field=models.TextField(blank=True, null=True, verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_skype',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_telegram',
            field=models.TextField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_twitter',
            field=models.TextField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_viber',
            field=models.TextField(blank=True, null=True, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_vk',
            field=models.TextField(blank=True, null=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_whatsapp',
            field=models.TextField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_work_time',
            field=models.TextField(blank=True, null=True, verbose_name='Графики работы'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='soc_youtube',
            field=models.TextField(blank=True, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='web_alias',
            field=models.TextField(blank=True, null=True, verbose_name='Web-Алиас'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='web_sites',
            field=models.TextField(blank=True, null=True, verbose_name='Веб сайты'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='branch_legal_name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Юр. название филиала'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='branch_org_name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='ОПФ филиала'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='categories',
            field=models.TextField(blank=True, null=True, verbose_name='Рубрики'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='division',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='division_extension',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Расширение подразделения'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='extension_addition',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Дополнение к расширению'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_facebook',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_google_plus',
            field=models.TextField(blank=True, null=True, verbose_name='GooglePlus'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_icq',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Icq'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_instagram',
            field=models.TextField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_linkedin',
            field=models.TextField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_odnoklassniki',
            field=models.TextField(blank=True, null=True, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_pinterest',
            field=models.TextField(blank=True, null=True, verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_skype',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_telegram',
            field=models.TextField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_twitter',
            field=models.TextField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_viber',
            field=models.TextField(blank=True, null=True, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_vk',
            field=models.TextField(blank=True, null=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_whatsapp',
            field=models.TextField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_work_time',
            field=models.TextField(blank=True, null=True, verbose_name='Графики работы'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='soc_youtube',
            field=models.TextField(blank=True, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='web_alias',
            field=models.TextField(blank=True, null=True, verbose_name='Web-Алиас'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='web_sites',
            field=models.TextField(blank=True, null=True, verbose_name='Веб сайты'),
        ),
    ]
