# Generated by Django 4.0.8 on 2022-11-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_dgisrecord_branch_legal_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dgisrecord',
            options={'verbose_name': 'Запись 2ГИС', 'verbose_name_plural': 'Записи 2ГИС'},
        ),
        migrations.AlterModelOptions(
            name='historicaldgisrecord',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Запись 2ГИС', 'verbose_name_plural': 'historical Записи 2ГИС'},
        ),
    ]
