# Generated by Django 4.0.8 on 2023-01-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_cityrecord_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityrecord',
            name='city',
            field=models.CharField(max_length=2048, unique=True, verbose_name='Город'),
        ),
    ]
