# Generated by Django 4.0.8 on 2023-01-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_alter_cityrecord_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityrecord',
            name='city',
            field=models.CharField(max_length=2048, verbose_name='Город'),
        ),
        migrations.AlterUniqueTogether(
            name='cityrecord',
            unique_together={('city', 'region')},
        ),
    ]
