# Generated by Django 4.0.8 on 2023-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_alter_cityrecord_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgisrecord',
            name='clat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='dgisrecord',
            name='clong',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='historicaldgisrecord',
            name='clat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='historicaldgisrecord',
            name='clong',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
