# Generated by Django 4.0.8 on 2023-01-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_dgisrecord_clat_dgisrecord_clong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgisrecord',
            name='city',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='historicaldgisrecord',
            name='city',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Город'),
        ),
    ]
