# Generated by Django 4.0.8 on 2023-01-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_dgisrecord_city_historicaldgisrecord_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='address',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='building_purpose',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Назначение здания'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='emails',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса электронной почты'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='extension',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Расширение'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='inn_ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='ИНН/ОГРН'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='number_of_floors',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='org_form',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='ОПФ'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='phone_area_code',
            field=models.TextField(blank=True, null=True, verbose_name='Код телефонной зоны'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='phones',
            field=models.TextField(blank=True, null=True, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='project_publications',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='street',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='unit',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Единица территориального деления'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='address',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='building_purpose',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Назначение здания'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='emails',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса электронной почты'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='extension',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Расширение'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='inn_ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='ИНН/ОГРН'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='number_of_floors',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='org_form',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='ОПФ'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='phone_area_code',
            field=models.TextField(blank=True, null=True, verbose_name='Код телефонной зоны'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='phones',
            field=models.TextField(blank=True, null=True, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='project_publications',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='street',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='unit',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Единица территориального деления'),
        ),
    ]
