# Generated by Django 4.0.8 on 2023-01-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_alter_dgisrecord_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisrecord',
            name='brand',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='dgisrecord',
            name='legal_name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Юр. название'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='brand',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='historicaldgisrecord',
            name='legal_name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Юр. название'),
        ),
    ]
