# Generated by Django 4.0.8 on 2023-01-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_alter_dgisrecord_brand_alter_dgisrecord_legal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='gt',
            field=models.CharField(max_length=255, verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='out_retail',
            field=models.PositiveIntegerField(verbose_name='Розница'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='out_total',
            field=models.PositiveIntegerField(verbose_name='Всего продано'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='out_whosale',
            field=models.PositiveIntegerField(verbose_name='Опт'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='gt',
            field=models.CharField(max_length=255, verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='out_retail',
            field=models.PositiveIntegerField(verbose_name='Розница'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='out_total',
            field=models.PositiveIntegerField(verbose_name='Всего продано'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='out_whosale',
            field=models.PositiveIntegerField(verbose_name='Опт'),
        ),
    ]
