# Generated by Django 4.0.8 on 2023-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_alter_chzrecord_gt_alter_chzrecord_out_retail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='pg_name',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='producer_name',
            field=models.CharField(max_length=255, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='pg_name',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='producer_name',
            field=models.CharField(max_length=255, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Продукт'),
        ),
    ]
