# Generated by Django 4.0.8 on 2023-01-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_alter_chzrecord_pg_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='prid',
            field=models.CharField(max_length=255, verbose_name='ИНН производителя'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='prid',
            field=models.CharField(max_length=255, verbose_name='ИНН производителя'),
        ),
    ]
