# Generated by Django 4.0.8 on 2023-01-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_alter_chzrecord_prid_alter_historicalchzrecord_prid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН поставщика'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН поставщика'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name='Поставщик'),
        ),
    ]
