# Generated by Django 4.0.8 on 2023-01-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_alter_chzrecord_inn_alter_chzrecord_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН продавца'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН продавца'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name='Продавец'),
        ),
    ]
