# Generated by Django 4.0.8 on 2023-01-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_alter_chzrecord_inn_alter_chzrecord_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='inn',
            field=models.PositiveBigIntegerField(verbose_name='ИНН продавца'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='inn',
            field=models.PositiveBigIntegerField(verbose_name='ИНН продавца'),
        ),
    ]
