# Generated by Django 4.0.8 on 2023-01-26 10:24

from django.db import migrations, models

sql = """
CREATE MATERIALIZED VIEW gtin_records AS
SELECT "data_chzrecord"."gt" AS id,
       "data_chzrecord"."product_name" AS product_name,
       COUNT("data_chzrecord"."gt") AS total
FROM "data_chzrecord"
GROUP BY "data_chzrecord"."gt",
         "data_chzrecord"."product_name"
ORDER BY "total" DESC;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_alter_chzrecord_inn_alter_historicalchzrecord_inn'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(sql, [])],
            reverse_sql=[("DROP MATERIALIZED VIEW gtin_records;")],
        )
    ]
