# Generated by Django 4.0.8 on 2023-02-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_create_gtin_mv'),
    ]

    operations = [
        migrations.AddField(
            model_name='chzrecord',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchzrecord',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
