# Generated by Django 4.0.8 on 2023-02-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_gtinrecordmv_chzrecord_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chzrecord',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='historicalchzrecord',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Позиция'),
        ),
    ]
