# Generated by Django 4.0.8 on 2023-02-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_gtinrecordmv_chzrecord_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='in_russia',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='mrp',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='out_recycle',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='out_retail',
            field=models.PositiveSmallIntegerField(verbose_name='Розница'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='out_total',
            field=models.PositiveSmallIntegerField(verbose_name='Всего продано'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='out_whosale',
            field=models.PositiveSmallIntegerField(verbose_name='Опт'),
        ),
        migrations.AlterField(
            model_name='chzrecord',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='gt',
            field=models.PositiveBigIntegerField(verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='in_russia',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='mrp',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='out_recycle',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='out_retail',
            field=models.PositiveSmallIntegerField(verbose_name='Розница'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='out_total',
            field=models.PositiveSmallIntegerField(verbose_name='Всего продано'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='out_whosale',
            field=models.PositiveSmallIntegerField(verbose_name='Опт'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
