# Generated by Django 4.0.8 on 2023-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_gtinrecordmv_alter_chzrecord_gt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chzrecord',
            name='gt',
            field=models.CharField(max_length=16, verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='historicalchzrecord',
            name='gt',
            field=models.CharField(max_length=16, verbose_name='GTIN'),
        ),
    ]
