# Generated by Django 4.0.8 on 2023-02-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_gtinrecordmv_alter_chzrecord_gt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTINRecordMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1024)),
                ('total', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'gtin_records',
                'managed': False,
            },
        ),
        migrations.AddIndex(
            model_name='chzrecord',
            index=models.Index(fields=['gt'], name='data_chzrec_gt_7cc6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='chzrecord',
            index=models.Index(fields=['inn'], name='data_chzrec_inn_0fb45c_idx'),
        ),
        migrations.AddIndex(
            model_name='chzrecord',
            index=models.Index(fields=['product_name'], name='data_chzrec_product_645fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='chzrecord',
            index=models.Index(fields=['weight'], name='data_chzrec_weight_e8d245_idx'),
        ),
        migrations.AddIndex(
            model_name='chzrecord',
            index=models.Index(fields=['position'], name='data_chzrec_positio_f43406_idx'),
        ),
        migrations.AddIndex(
            model_name='chzrecord',
            index=models.Index(fields=['date'], name='data_chzrec_date_dceb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='dgisrecord',
            index=models.Index(fields=['project_publications'], name='data_dgisre_project_256294_idx'),
        ),
    ]
