# Generated by Django 4.0.8 on 2023-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_gtinrecordmv_chzrecord_data_chzrec_gt_7cc6c0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCGTINRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=16, verbose_name='GTIN')),
                ('product_name', models.CharField(max_length=1024)),
                ('retail_sales', models.PositiveSmallIntegerField()),
                ('region', models.CharField(blank=True, max_length=512, null=True, verbose_name='Регион')),
                ('group', models.CharField(max_length=16, verbose_name='Группа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'unique_together': {('gtin', 'region')},
            },
        ),
    ]
