# Generated by Django 4.0.8 on 2023-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_abcgtinrecord_acc_retail_sales_share_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcgtinrecord',
            options={'verbose_name': 'Запись Отчета: ABC-анализ розничные продажи по регионам', 'verbose_name_plural': 'Записи Отчета: ABC-анализ розничные продажи по регионам'},
        ),
        migrations.AddField(
            model_name='abcgtinrecord',
            name='total_sales',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
