# Generated by Django 4.0.8 on 2023-03-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_alter_abcgtinrecord_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABCGTINRecord',
        ),
    ]
