# Generated by Django 4.0.8 on 2023-03-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_delete_abcgtinrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityRecord',
            new_name='City',
        ),
    ]
