# Generated by Django 4.0.8 on 2023-03-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_dgisplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgisrecord',
            name='dgis_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.dgisplace'),
        ),
        migrations.AddField(
            model_name='historicaldgisrecord',
            name='dgis_place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.dgisplace'),
        ),
    ]
