# Generated by Django 4.0.8 on 2023-03-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_alter_dgisplace_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgisplace',
            name='subregion',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
