# Generated by Django 4.0.8 on 2023-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_alter_dgisrecord_dgis_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisplace',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='dgisplace',
            name='street_num',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Номер'),
        ),
    ]
