version: "3.9"

networks:

  proxy: # docker network create --driver=overlay --internal=false --attachable proxy
    attachable: true
    internal: false
    name: proxy


services:
  redis:
    image: redis:5
    container_name: server-redis
    restart: always
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
