tls_server_config:
  cert_file: /etc/node_exporter/node_exporter.crt
  key_file: /etc/node_exporter/node_exporter.key
basic_auth_users:
  eatchefs_stage: $2y$10$Gx6YS0U8wgKr1.G9JUh.GeThnL1sjhbk6p5G8iN7d/he/3i66MV8C
